Initial support for gdb debugging in Hyperlight KVM guest
hyperlight-dev/hyperlight pull request #111
Opened 2024-12-13 17:54 UTC by dblnz

- The current implementation supports only 4 hardware breakpoints.
- There might be some bugs, I am still testing
- There are some modifications I plan on doing but shouldn't have big impact on this solution

2025-01-22 12:29 UTC, devigned requested changes
Super excited to see this landing. Nice work! My feedback mostly consists of nits and questions.

2025-01-22 12:29 UTC, devigned commented on docs/how-to-debug-a-hyperlight-guest.md
> +Currently Hyperlight support gdb debugging of a guest running inside a Hyperlight sandbox.
```suggestion
Hyperlight supports gdb debugging of a guest running inside a Hyperlight sandbox.
```

2025-01-22 12:29 UTC, devigned commented on docs/how-to-debug-a-hyperlight-guest.md
> +When the option is enabled Hyperlight starts listening on port `8081` for a gdb connection.
```suggestion
When Hyperlight is compiled with the `gdb` feature enabled, Hyperlight starts listening on port `8081` for a gdb connection.
```

2025-01-22 12:29 UTC, devigned commented on docs/how-to-debug-a-hyperlight-guest.md
> +of `.gdbinit` file can be used.
Please either explain what the file does specifically, or provide a link to .gdbinit file documentation.

2025-01-22 12:29 UTC, devigned commented on src/hyperlight_host/src/hypervisor/gdb/mod.rs
> +            _ => GdbTargetError::UnexpectedMessageError,
Why are you matching on value only to return the same error?

2025-01-22 12:29 UTC, devigned commented on src/hyperlight_host/src/hypervisor/gdb/mod.rs
> +    // TODO: Address multiple sandboxes scenario
Rather than have a code comment, please create a new issue in the repo to track the feature.

2025-01-22 12:29 UTC, devigned commented on src/hyperlight_host/src/hypervisor/gdb/target.rs
> +        // TODO: Properly handle errors
What would you like to do based on this TODO?

A related nit, it would be nice to have some preservation of the data in the underlying error, so as the error bubbles up, we can determine the root cause.

2025-01-22 12:29 UTC, devigned commented on src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
> +    shm: Arc<Mutex<Option<Arc<Mutex<SandboxMemoryManager<GuestSharedMemory>>>>>>,
Do you intend on changing this prior to PR merging?

2025-01-22 12:29 UTC, devigned commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +            .map_err(|_| new_error!("Cannot set entrypoint breakpoint"))?;
Is there useful information in the underlying error?

2025-01-22 15:43 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/gdb/mod.rs
> +            _ => GdbTargetError::UnexpectedMessageError,
This was something I missed, I'll change it, thanks for pointing it out

2025-01-22 15:44 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/gdb/mod.rs
> +    // TODO: Address multiple sandboxes scenario
I'll do that after I gather all the feedback as this might be addressed before merging

2025-01-22 15:46 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/gdb/target.rs
> +        // TODO: Properly handle errors
This was a left over comment from the development phase, I added some error handling in the meantime. 
I would like to maybe get an idea as to how to redo the error handling to be easier to track where errors originated

2025-01-22 15:49 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
> +    shm: Arc<Mutex<Option<Arc<Mutex<SandboxMemoryManager<GuestSharedMemory>>>>>>,
I would like to change it.
Cloning  `SandboxMemoryManager` directly might be a better idea, but the `GuestSharedMemory` type does not implement Clone, I need to check what implementing that would mean.

2025-01-22 15:50 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +            .map_err(|_| new_error!("Cannot set entrypoint breakpoint"))?;
It is a KVM generated error, I need to think about how to propagate the errors

2025-01-28 00:44 UTC, danbugs commented on src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
> +    shm: Arc<Mutex<Option<Arc<Mutex<SandboxMemoryManager<GuestSharedMemory>>>>>>,
Does `KVMDriver` need a clone of SandboxMemoryManager or does a mutable borrow maybe suffice? `GuestSharedMemory` was purposefully not `Clone` because it was intended to reflect unique ownership at any time of the guest side access to the shared memory.

2025-01-28 00:44 UTC, danbugs commented on src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
> +        #[cfg(not(gdb))]
Disabling the timeout might be helpful for scenarios other than debugging too. Might want to put this under a different feature flag or even as a runtime option. Though, that's not too related to this PR, so maybe leaving it like this is OK for now 👍

2025-02-05 04:50 UTC, ludfjig submitted a review, later dismissed
This is awesome!! Looked briefly though everything and I will give a more in-depth review tomorrow

2025-02-05 04:50 UTC, ludfjig commented on src/hyperlight_host/Cargo.toml
> +gdbstub = "0.7.3"
Is it possible to make these optional dependencies that are only included when the `gdb` feature is turned on?

2025-02-05 04:50 UTC, ludfjig commented on src/hyperlight_host/src/hypervisor/gdb/mod.rs
> +/// Struct that contains the x86_64 core registers
nit: I personally prefer the comment above the #[derive], but up to you :D

2025-02-05 04:50 UTC, ludfjig commented on src/hyperlight_host/src/sandbox/config.rs
> +    pub const MIN_GUEST_DEBUG_PORT: u16 = 9000;
Is there a reason the port must be >=9000? Otherwise the name could be DEFAULT_GUEST_DEBUG_PORT

2025-02-05 04:50 UTC, ludfjig commented on src/hyperlight_host/src/hypervisor/gdb/x86_64_target.rs
> +                    .expect("Couldn't convert rflags from u64 to u32");
Perhaps we should return an error instead of panic here

2025-02-05 08:14 UTC, dblnz commented on src/hyperlight_host/Cargo.toml
> +gdbstub = "0.7.3"
good point, I'll do that

2025-02-05 08:18 UTC, dblnz commented on src/hyperlight_host/src/sandbox/config.rs
> +    pub const MIN_GUEST_DEBUG_PORT: u16 = 9000;
I wanted to have this constraint to not interfere with any other services that might be running on the machine, but I thing the MIN should be around 1024.

2025-02-05 08:26 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/gdb/x86_64_target.rs
> +                    .expect("Couldn't convert rflags from u64 to u32");
I've missed this, I'll change it

2025-02-05 12:58 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/gdb/mod.rs
> +/// Struct that contains the x86_64 core registers
You are right, it looks weird this way. I changed it

2025-02-07 05:39 UTC, ludfjig approved these changes
This is awesome. I tried it out and it works great. Left some more comments, feel free to dismiss if you disagree with any of them. I realize some of them might be hard to implement as well. GREAT WORK!!

2025-02-07 05:39 UTC, ludfjig commented on src/hyperlight_host/src/sandbox/config.rs
> +        self.guest_debug_port = Some(max(port, Self::MIN_GUEST_DEBUG_PORT));
I called this function but forgot to enable the gdb feature. The code ran fine, but didn't wait for gdb to connect, and I got confused. In my opinion, maybe we should feature-gate this function, or return error somewhere (maybe not in this func) if a user is trying to use a sandbox with this setting set, without using the gdb feature. Maybe others have better ideas. Maybe some tests for this could be good to

2025-02-07 05:39 UTC, ludfjig commented on docs/how-to-debug-a-hyperlight-guest.md
> +Using the [Sandbox configuration](#sandbox-configuration) above to configure the [hello-world](https://github.com/hyperlight-dev/hyperlight/blob/main/src/hyperlight_host/examples/hello-world/main.rs)
I think it would be useful if we created a brand new example for this instead of using hello-world. I read through this doc but missed the part where it said "Using the sandbox configuration above", so I was confused why it wasn't working. What do you think?

2025-02-07 05:39 UTC, ludfjig commented on docs/how-to-debug-a-hyperlight-guest.md
> +file file src/tests/rust_guests/bin/debug/simpleguest
file file typo?

2025-02-07 05:39 UTC, ludfjig commented on src/hyperlight_host/Cargo.toml
> +# This enables compilation of gdb stub for easy debug in the guest
I think you can drop the first part of this comment, since we probably don't care too much about what compilation it enables, but rather that it allows for easy gdb debugging of a guest.

2025-02-07 05:39 UTC, ludfjig commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +                self.dbg_cfg.arch.debugreg[7] |= 1 << (k * 2);
Would you mind adding a comment about what these bit operations does/means?

2025-02-07 05:39 UTC, ludfjig commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +                Some(create_gdb_thread(*port).map_err(|_| new_error!("Cannot create GDB thread"))?),
To me it doesn't seem right to create the gdb thread from the KVM driver. In the future, we might support debugging on mshv, in which case we'd probably want to create this after the particular driver has been created. Do you think it's possible to move this somewhere else?

2025-02-07 05:39 UTC, ludfjig commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +mod debug {
Is there any chance we could move this to it's own file? I understand kvm_guest_debug struct is kvm-specific, but otherwise the rest seems pretty generic to me, and to me it makes sense moving the gdb specific stuff out of the kvm.rs driver code. Hopefully it's possible :P

2025-02-07 05:39 UTC, ludfjig commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +                entrypoint_debug.hw_breakpoints.push(self.entrypoint);
Could we make an method on KvmDebug for adding a breakpoint that does error checking (>4 breapoints), instead of manually modifying the vec? It seems fragile to do the error checking during the `set_breakpoints`, and to expose the inner vec like this.

2025-02-07 05:39 UTC, ludfjig commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +                if debug.hw_breakpoints.contains(&addr) {
Seems like the `.contains` is unnecessary given that you use `.position` later anyway. You might be able to simplify this whole block using `hw_breakpoints.retain(|a| a != addrv)` or something along those lines

2025-02-07 05:39 UTC, ludfjig commented on src/hyperlight_host/src/hypervisor/gdb/event_loop.rs
> +            if conn.peek().map(|b| b.is_some()).unwrap_or(false) {
I'm not sure I really understand what this is doing. Maybe a comment here could help

2025-02-07 05:39 UTC, ludfjig commented on src/hyperlight_host/src/hypervisor/gdb/mod.rs
> +    AddHwBreakpoint(bool),
Do we need all of these responses, or would it be sufficient to combine some of them into something like Success()? I looked briefly and I didn't see `AddHwBreakpoint` and `AddSwBreakpoint` being used for anything for example. ( can see DebugResponse::Step | DebugResponse::Continue | DebugResponse::DisableDebug are being used though)

2025-02-07 05:39 UTC, ludfjig commented on docs/how-to-debug-a-hyperlight-guest.md
> +$ gdb
This markdown is great. One thing this gdb feature introduces is some complexity regarding threading. Would you be able to write down (or maybe create a diagram) for how the threads interact with each other, for example the handler thread and so on? It's a bit confusing to me which thread waits for what thread, etc :D

2025-02-07 09:03 UTC, dblnz commented on src/hyperlight_host/src/sandbox/config.rs
> +        self.guest_debug_port = Some(max(port, Self::MIN_GUEST_DEBUG_PORT));
This was the previous intention, however, I disabled it with the last commit.
The reasoning behind was that the rust-analyzer didn't know about the feature being enabled and it showed errors in IDE as it doesn't know the methods.
I am not sure which is the best approach, you might be right with being confusing when it doesn't do anything.

2025-02-07 09:03 UTC, dblnz commented on docs/how-to-debug-a-hyperlight-guest.md
> +Using the [Sandbox configuration](#sandbox-configuration) above to configure the [hello-world](https://github.com/hyperlight-dev/hyperlight/blob/main/src/hyperlight_host/examples/hello-world/main.rs)
Good point, I can add another example

2025-02-07 09:07 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +                Some(create_gdb_thread(*port).map_err(|_| new_error!("Cannot create GDB thread"))?),
It doesn't need to be there anymore, since the big change.
However, the specific hypervisor would have to own the connection to `gdb` for it to be able to receive/send messages.

2025-02-07 09:08 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +mod debug {
Well, part of it is possible, the KvmDebug type specifically, however the rest of the implementation is for the `KVMDriver` so it cannot be moved out of the file the type is defined, right?

2025-02-07 09:09 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +                entrypoint_debug.hw_breakpoints.push(self.entrypoint);
good point, I'll change it 👍

2025-02-07 09:11 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +                if debug.hw_breakpoints.contains(&addr) {
thanks for the suggestion

2025-02-07 09:14 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/gdb/event_loop.rs
> +            if conn.peek().map(|b| b.is_some()).unwrap_or(false) {
I'll add a comment

2025-02-07 09:18 UTC, dblnz commented on src/hyperlight_host/src/hypervisor/gdb/mod.rs
> +    AddHwBreakpoint(bool),
The need stems from the return value the `add_sw_breakpoint` and the others expect.
An example signature is:
```
    fn add_sw_breakpoint(
        &mut self,
        addr: <Self::Arch as Arch>::Usize,
        _kind: <Self::Arch as Arch>::BreakpointKind,
    ) -> TargetResult<bool, Self> {
```

and it expects true/false on the success path signaling whether the breakpoint is active, true being it was just added, false being it was already active and the new call didn't actually do anything.

2025-02-07 09:23 UTC, dblnz commented on docs/how-to-debug-a-hyperlight-guest.md
> +$ gdb
this is a good idea, I thought about adding a diagram but I was afraid it would get desynchronized with the code when there would be a change as the documentation usually doesn't get updated unless it is close to the code being changed.

I'll work on a diagram to help with the understanding of the inner workings of the feature.

2025-02-07 17:53 UTC, ludfjig commented on src/hyperlight_host/src/sandbox/config.rs
> +        self.guest_debug_port = Some(max(port, Self::MIN_GUEST_DEBUG_PORT));
You should be able to enable the feature for rust-analyzer in .vscode/settings.json

2025-02-11 11:46 UTC, simongdavies requested changes
a few minor issues, but overall this is great. I don't know why the spelling issues are not getting picked up by the spell check in GH actions

2025-02-11 11:46 UTC, simongdavies commented on docs/how-to-debug-a-hyperlight-guest.md
> +1. KVM guest debugging:
Should we call out more clearly that this only works on KVM for now?

2025-02-11 11:46 UTC, simongdavies commented on docs/how-to-debug-a-hyperlight-guest.md
> +a thread that accepts commands from a gdb cliend and the hypervisor handler over
```suggestion
a thread that accepts commands from a gdb client and the hypervisor handler over
```

2025-02-11 11:46 UTC, simongdavies commented on docs/how-to-debug-a-hyperlight-guest.md
> +```
I think it would be useful to have a walkthrough of how to set up debugging using vscode with a few screenshots etc. ?

2025-02-11 11:46 UTC, simongdavies commented on src/hyperlight_host/build.rs
> +        gdb: { all(feature = "gdb", debug_assertions, target_os = "linux") },
Since right now we only support debugging with kvm should we be explicit about that here? (and maybe fail with a compilation error if kvm is not set and debug is)

2025-02-11 11:46 UTC, simongdavies commented on src/hyperlight_host/src/hypervisor/gdb/mod.rs
> +/// Defines the possible reasons for which a vCPU ce be stopped when debugging
```suggestion
/// Defines the possible reasons for which a vCPU can be stopped when debugging
```

2025-02-11 11:46 UTC, simongdavies commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +    /// Software Breakpoinnt opcode
```suggestion
    /// Software Breakpoint opcode
```

2025-02-11 11:46 UTC, simongdavies commented on src/hyperlight_host/src/sandbox/mem_access.rs
> +
is there a reason why these functions are not gated by the gdb feature?

2025-02-11 14:09 UTC, dblnz commented on docs/how-to-debug-a-hyperlight-guest.md
> +1. KVM guest debugging:
It might be better to advertise it as only for KVM for now

2025-02-11 14:09 UTC, dblnz commented on docs/how-to-debug-a-hyperlight-guest.md
> +a thread that accepts commands from a gdb cliend and the hypervisor handler over
Weird I haven't spotted (I enabled a couple of local tools for spelling) it and neither did the typo checker.

2025-02-11 16:53 UTC, syntactically reviewed
I really like how this looks overall! I've left a few small things in the code comments. I also have a couple of nits about the commit organization:

Commit message for 579b3249: s/tread/thread/

Commits b175f416, af0a52a5, 6cc61849, and 98ac60ea: please convert
each one to a series of fixup! commits to the original commits
introducing code, so that we can autosquash before merging, or just
rebase the changes into the original commits now if nobody else
objects to that.

2025-02-11 16:53 UTC, syntactically commented on src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
> +        #[cfg(gdb)]
Maybe include a comment here mentioning why this is? (I presume it's because the thread may pause for a long time waiting for gdb commands?)

2025-02-11 16:53 UTC, syntactically commented on src/hyperlight_host/src/sandbox/config.rs
> +    pub const MIN_GUEST_DEBUG_PORT: u16 = 9000;
I agree with @ludfjig that an arbitrary minimum of 9000 here is not great. You probably don't need to do anything special to prevent ports below 1024, since Linux won't allow binding those without CAP_NET_BIND_SERVICE (by default granted only to root processes) anyway.

2025-02-11 16:53 UTC, syntactically commented on src/hyperlight_host/src/sandbox/uninitialized.rs
> +pub struct DebugInfo {
Why do we have this struct? If the goal is to make it easy to pass more information that's needed for the debug configuration in the future, should the `SandboxConfiguration` directly contain one of these, instead of a raw port?

2025-02-11 16:53 UTC, syntactically commented on src/hyperlight_host/src/hypervisor/gdb/event_loop.rs
> +    fn on_interrupt(
I'm slightly confused here---it looks to me like this is reporting to the gdbstub state machine that the thread has stopped, but isn't actually stopping it? We could accomplish actually stopping it by sending a signal to the handler thread to kick the vcpu, or report an error if we don't want to support it?

2025-02-11 16:53 UTC, syntactically commented on src/hyperlight_host/src/hypervisor/gdb/x86_64_target.rs
> +                    .expect("Couldn't convert rflags from u64 to u32");
I think that the extra bits in `rflags` vs `eflags` are currently reserved, but going by the general x86 conventions, I would expect `eflags` to always refer to the bottom half of `rflags`, so maybe instead of doing a checked conversion here it's semantically cleaner to just truncate?

2025-02-11 16:53 UTC, syntactically commented on src/hyperlight_host/src/sandbox/mem_access.rs
> +    mut wrapper: MemMgrWrapper<HostSharedMemory>,
Instead of cloning the hshm wraper 3 times to allow it to be closed over by 3 independent closures, why not define a struct that contains a single hshm wrapper and implements the handler trait directly, or perhaps do away with the trait entirely and pass the wrapper directly to the kvm/gdb thread?

2025-02-11 16:53 UTC, syntactically commented on src/hyperlight_host/src/hypervisor/gdb/mod.rs
> +    AddHwBreakpoint(bool),
I think the extra semantic information of the extra variants is probably useful

2025-02-11 16:53 UTC, syntactically commented on src/hyperlight_host/src/hypervisor/gdb/x86_64_target.rs
> +        true
The gdbstub docs seem to imply that this should only be true when we don't implement our own support for sw breakpoints, since this lets gdb do it by itself?

2025-02-11 16:53 UTC, syntactically commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +            let mut save_data = [0; SW_BP_SIZE];
Do we need to make sure that when resuming after a software breakpoint we put the saved instruction back, single step, and then replace it with brk again? Or does the gdb frontend guarantee it will call remove/add_breakpoint in the correct sequence for that, in which case we should probably have a note about that?

2025-02-19 07:20 UTC, ludfjig approved these changes
LGTM!

2025-02-19 07:20 UTC, ludfjig commented on docs/how-to-debug-a-hyperlight-guest.md
> +Hyperlight supports gdb debugging of a **KVM** guest running inside a Hyperlight sandbox.
this is great document!

2025-02-19 12:37 UTC, simongdavies submitted a review, later dismissed

2025-02-19 14:36 UTC, devigned submitted a review, later dismissed
lgtm! Great work, @dblnz!

2025-02-19 19:35 UTC, syntactically commented on src/hyperlight_host/src/hypervisor/gdb/event_loop.rs
> +    fn on_interrupt(
The new version seems less likely to mess up the state machine, but is it better UX to eagerly report the fact that we don't stop this by sending an error back?

2025-02-19 19:35 UTC, syntactically commented on src/hyperlight_host/src/hypervisor/handlers.rs
> +pub type DbgMemAccessHandlerWrapper = Arc<Mutex<dyn DbgMemAccessHandlerCaller>>;
Honestly, given that there's only really one sensible implementation of this, I somewhat question the utility of making it into a trait like this at all... though that also applies to the other exact handlers, tbh.

2025-02-19 19:35 UTC, syntactically commented on src/hyperlight_host/src/hypervisor/kvm.rs
> +        /// For more information see: https://en.wikipedia.org/wiki/X86_debug_register
Instead of a (mutable) wikipedia page, can we cite the architecture manual here?

2025-02-21 13:58 UTC, syntactically approved these changes

2025-02-21 17:15 UTC, ludfjig approved these changes

2025-02-21 19:35 UTC, merged